//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chatEntities : DbContext
    {
        public chatEntities()
            : base("name=chatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<amigo> amigo { get; set; }
        public virtual DbSet<chat> chat { get; set; }
        public virtual DbSet<mensaje> mensaje { get; set; }
        public virtual DbSet<reaccion> reaccion { get; set; }
        public virtual DbSet<usuariochat> usuariochat { get; set; }
    }
}
