//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class mensaje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mensaje()
        {
            this.reaccion = new HashSet<reaccion>();
        }
    
        public int idMensaje { get; set; }
        public System.DateTime fecha { get; set; }
        public sbyte favorito { get; set; }
        public string mensaje1 { get; set; }
        public int TipoMensaje_idTipoMensaje { get; set; }
        public int Chat_idChat { get; set; }
        public string tipoMensaje { get; set; }
        public int idMensajeImagen { get; set; }
        public int idMensajeAudio { get; set; }
    
        public virtual chat chat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reaccion> reaccion { get; set; }
    }
}
