//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChatDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class reaccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reaccion()
        {
            this.mensaje = new HashSet<mensaje>();
        }
    
        public int idReaccion { get; set; }
        public string nombre { get; set; }
        public int UsuarioChat_idUsuarioChat { get; set; }
    
        public virtual usuariochat usuariochat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mensaje> mensaje { get; set; }
    }
}
