-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 19:42:38 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estado
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `estado` ;

-- -----------------------------------------------------
-- Schema estado
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estado` DEFAULT CHARACTER SET utf8 ;
USE `estado` ;

-- -----------------------------------------------------
-- Table `estado`.`UsuarioEstado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`UsuarioEstado` ;

CREATE TABLE IF NOT EXISTS `estado`.`UsuarioEstado` (
  `idUsuarioEstado` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idUsuarioEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estado`.`Estado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`Estado` ;

CREATE TABLE IF NOT EXISTS `estado`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `UsuarioEstado_idUsuarioEstado` INT NOT NULL,
  `idEstadoImagen` INT NULL,
  PRIMARY KEY (`idEstado`),
  INDEX `fk_Estado_UsuarioEstado_idx` (`UsuarioEstado_idUsuarioEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_UsuarioEstado`
    FOREIGN KEY (`UsuarioEstado_idUsuarioEstado`)
    REFERENCES `estado`.`UsuarioEstado` (`idUsuarioEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estado`.`Reaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`Reaccion` ;

CREATE TABLE IF NOT EXISTS `estado`.`Reaccion` (
  `idReaccion` INT NOT NULL AUTO_INCREMENT,
  `nombreReaccion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idReaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estado`.`Estado_has_Reaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`Estado_has_Reaccion` ;

CREATE TABLE IF NOT EXISTS `estado`.`Estado_has_Reaccion` (
  `Estado_idEstado` INT NOT NULL,
  `Reaccion_idReaccion` INT NOT NULL,
  PRIMARY KEY (`Estado_idEstado`, `Reaccion_idReaccion`),
  INDEX `fk_Estado_has_Reaccion_Reaccion1_idx` (`Reaccion_idReaccion` ASC) VISIBLE,
  INDEX `fk_Estado_has_Reaccion_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_Estado_has_Reaccion_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `estado`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estado_has_Reaccion_Reaccion1`
    FOREIGN KEY (`Reaccion_idReaccion`)
    REFERENCES `estado`.`Reaccion` (`idReaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estado`.`TipoEstado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `estado`.`TipoEstado` ;

CREATE TABLE IF NOT EXISTS `estado`.`TipoEstado` (
  `idTipoEstado` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(45) NOT NULL,
  `Estado_idEstado` INT NOT NULL,
  PRIMARY KEY (`idTipoEstado`),
  INDEX `fk_TipoEstado_Estado1_idx` (`Estado_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_TipoEstado_Estado1`
    FOREIGN KEY (`Estado_idEstado`)
    REFERENCES `estado`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
