//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioCuentaUsuario
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cuenta", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCuentaUsuario")]
    public partial class Cuenta : object
    {
        
        private int Genero_idGeneroField;
        
        private int idCuentaField;
        
        private int idFotoCuentaUsuarioField;
        
        private string nombreUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Genero_idGenero
        {
            get
            {
                return this.Genero_idGeneroField;
            }
            set
            {
                this.Genero_idGeneroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCuenta
        {
            get
            {
                return this.idCuentaField;
            }
            set
            {
                this.idCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idFotoCuentaUsuario
        {
            get
            {
                return this.idFotoCuentaUsuarioField;
            }
            set
            {
                this.idFotoCuentaUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreUsuario
        {
            get
            {
                return this.nombreUsuarioField;
            }
            set
            {
                this.nombreUsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrasena", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCuentaUsuario")]
    public partial class Contrasena : object
    {
        
        private int Cuenta_idCuentaField;
        
        private string contrasenaField;
        
        private int idContrasenaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cuenta_idCuenta
        {
            get
            {
                return this.Cuenta_idCuentaField;
            }
            set
            {
                this.Cuenta_idCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string contrasena
        {
            get
            {
                return this.contrasenaField;
            }
            set
            {
                this.contrasenaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idContrasena
        {
            get
            {
                return this.idContrasenaField;
            }
            set
            {
                this.idContrasenaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Correo", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCuentaUsuario")]
    public partial class Correo : object
    {
        
        private int Cuenta_idCuentaField;
        
        private string correoField;
        
        private int idCorreoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cuenta_idCuenta
        {
            get
            {
                return this.Cuenta_idCuentaField;
            }
            set
            {
                this.Cuenta_idCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string correo
        {
            get
            {
                return this.correoField;
            }
            set
            {
                this.correoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCorreo
        {
            get
            {
                return this.idCorreoField;
            }
            set
            {
                this.idCorreoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telefono", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCuentaUsuario")]
    public partial class Telefono : object
    {
        
        private int Cuenta_idCuentaField;
        
        private int idTelefonoField;
        
        private string telefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cuenta_idCuenta
        {
            get
            {
                return this.Cuenta_idCuentaField;
            }
            set
            {
                this.Cuenta_idCuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTelefono
        {
            get
            {
                return this.idTelefonoField;
            }
            set
            {
                this.idTelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string telefono
        {
            get
            {
                return this.telefonoField;
            }
            set
            {
                this.telefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MensajeR", Namespace="http://schemas.datacontract.org/2004/07/ServiciosCuentaUsuario")]
    public partial class MensajeR : object
    {
        
        private bool errorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioCuentaUsuario.IServicioCuentaUsuario")]
    public interface IServicioCuentaUsuario
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/IniciarSesion", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/IniciarSesionResponse")]
        ServicioCuentaUsuario.Cuenta IniciarSesion(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/IniciarSesion", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/IniciarSesionResponse")]
        System.Threading.Tasks.Task<ServicioCuentaUsuario.Cuenta> IniciarSesionAsync(string correo, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuarioResponse")]
        ServicioCuentaUsuario.MensajeR RegistrarUsuario(ServicioCuentaUsuario.Cuenta cuenta, ServicioCuentaUsuario.Contrasena contrasena, ServicioCuentaUsuario.Correo correo, ServicioCuentaUsuario.Telefono telefono);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuario", ReplyAction="http://tempuri.org/IServicioCuentaUsuario/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<ServicioCuentaUsuario.MensajeR> RegistrarUsuarioAsync(ServicioCuentaUsuario.Cuenta cuenta, ServicioCuentaUsuario.Contrasena contrasena, ServicioCuentaUsuario.Correo correo, ServicioCuentaUsuario.Telefono telefono);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServicioCuentaUsuarioChannel : ServicioCuentaUsuario.IServicioCuentaUsuario, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServicioCuentaUsuarioClient : System.ServiceModel.ClientBase<ServicioCuentaUsuario.IServicioCuentaUsuario>, ServicioCuentaUsuario.IServicioCuentaUsuario
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioCuentaUsuarioClient() : 
                base(ServicioCuentaUsuarioClient.GetDefaultBinding(), ServicioCuentaUsuarioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioCuentaUsuarioClient.GetBindingForEndpoint(endpointConfiguration), ServicioCuentaUsuarioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioCuentaUsuarioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioCuentaUsuarioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCuentaUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServicioCuentaUsuario.Cuenta IniciarSesion(string correo, string contrasena)
        {
            return base.Channel.IniciarSesion(correo, contrasena);
        }
        
        public System.Threading.Tasks.Task<ServicioCuentaUsuario.Cuenta> IniciarSesionAsync(string correo, string contrasena)
        {
            return base.Channel.IniciarSesionAsync(correo, contrasena);
        }
        
        public ServicioCuentaUsuario.MensajeR RegistrarUsuario(ServicioCuentaUsuario.Cuenta cuenta, ServicioCuentaUsuario.Contrasena contrasena, ServicioCuentaUsuario.Correo correo, ServicioCuentaUsuario.Telefono telefono)
        {
            return base.Channel.RegistrarUsuario(cuenta, contrasena, correo, telefono);
        }
        
        public System.Threading.Tasks.Task<ServicioCuentaUsuario.MensajeR> RegistrarUsuarioAsync(ServicioCuentaUsuario.Cuenta cuenta, ServicioCuentaUsuario.Contrasena contrasena, ServicioCuentaUsuario.Correo correo, ServicioCuentaUsuario.Telefono telefono)
        {
            return base.Channel.RegistrarUsuarioAsync(cuenta, contrasena, correo, telefono);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/ServiciosCuentaUsuario/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioCuentaUsuarioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioCuentaUsuarioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCuentaUsuario);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCuentaUsuario,
        }
    }
}
