//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadoDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estadoEntities : DbContext
    {
        public estadoEntities()
            : base("name=estadoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<reaccion> reaccion { get; set; }
        public virtual DbSet<tipoestado> tipoestado { get; set; }
        public virtual DbSet<usuarioestado> usuarioestado { get; set; }
    }
}
