//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstadoDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoestado
    {
        public int idTipoEstado { get; set; }
        public string tipo { get; set; }
        public int Estado_idEstado { get; set; }
    
        public virtual estado estado { get; set; }
    }
}
