//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultimediaDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class multimediaEntities : DbContext
    {
        public multimediaEntities()
            : base("name=multimediaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<direccion> direccion { get; set; }
        public virtual DbSet<estadoimagen> estadoimagen { get; set; }
        public virtual DbSet<fotocuentausuario> fotocuentausuario { get; set; }
        public virtual DbSet<mensajeaudio> mensajeaudio { get; set; }
        public virtual DbSet<mensajeimagen> mensajeimagen { get; set; }
    }
}
