//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuentaUsuarioDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuentasDeUsuario : DbContext
    {
        public CuentasDeUsuario()
            : base("name=CuentasDeUsuario")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contrasena> contrasena { get; set; }
        public virtual DbSet<correo> correo { get; set; }
        public virtual DbSet<cuenta> cuenta { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<telefono> telefono { get; set; }
    }
}
