-- MySQL Script generated by MySQL Workbench
-- Wed Dec 16 18:20:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Chat
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Chat` ;

-- -----------------------------------------------------
-- Schema Chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Chat` DEFAULT CHARACTER SET utf8 ;
USE `Chat` ;

-- -----------------------------------------------------
-- Table `Chat`.`Chat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chat`.`Chat` ;

CREATE TABLE IF NOT EXISTS `Chat`.`Chat` (
  `idChat` INT NOT NULL AUTO_INCREMENT,
  `nombreChat` VARCHAR(45) NOT NULL,
  `tipoChat` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idChat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat`.`Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chat`.`Mensaje` ;

CREATE TABLE IF NOT EXISTS `Chat`.`Mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `favorito` TINYINT NOT NULL,
  `mensaje` VARCHAR(1000) NULL,
  `TipoMensaje_idTipoMensaje` INT NOT NULL,
  `Chat_idChat` INT NOT NULL,
  `tipoMensaje` VARCHAR(45) NOT NULL,
  `idMensajeImagen` INT NOT NULL,
  `idMensajeAudio` INT NOT NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_Mensaje_Chat1_idx` (`Chat_idChat` ASC) VISIBLE,
  CONSTRAINT `fk_Mensaje_Chat1`
    FOREIGN KEY (`Chat_idChat`)
    REFERENCES `Chat`.`Chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat`.`UsuarioChat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chat`.`UsuarioChat` ;

CREATE TABLE IF NOT EXISTS `Chat`.`UsuarioChat` (
  `idUsuarioChat` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `Chat_idChat` INT NOT NULL,
  PRIMARY KEY (`idUsuarioChat`),
  INDEX `fk_UsuarioChat_Chat1_idx` (`Chat_idChat` ASC) VISIBLE,
  CONSTRAINT `fk_UsuarioChat_Chat1`
    FOREIGN KEY (`Chat_idChat`)
    REFERENCES `Chat`.`Chat` (`idChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat`.`Reaccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chat`.`Reaccion` ;

CREATE TABLE IF NOT EXISTS `Chat`.`Reaccion` (
  `idReaccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `UsuarioChat_idUsuarioChat` INT NOT NULL,
  PRIMARY KEY (`idReaccion`),
  INDEX `fk_Reaccion_UsuarioChat1_idx` (`UsuarioChat_idUsuarioChat` ASC) VISIBLE,
  CONSTRAINT `fk_Reaccion_UsuarioChat1`
    FOREIGN KEY (`UsuarioChat_idUsuarioChat`)
    REFERENCES `Chat`.`UsuarioChat` (`idUsuarioChat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat`.`Reaccion_has_Mensaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chat`.`Reaccion_has_Mensaje` ;

CREATE TABLE IF NOT EXISTS `Chat`.`Reaccion_has_Mensaje` (
  `Reaccion_idReaccion` INT NOT NULL AUTO_INCREMENT,
  `Mensaje_idMensaje` INT NOT NULL,
  PRIMARY KEY (`Reaccion_idReaccion`, `Mensaje_idMensaje`),
  INDEX `fk_Reaccion_has_Mensaje_Mensaje1_idx` (`Mensaje_idMensaje` ASC) VISIBLE,
  INDEX `fk_Reaccion_has_Mensaje_Reaccion1_idx` (`Reaccion_idReaccion` ASC) VISIBLE,
  CONSTRAINT `fk_Reaccion_has_Mensaje_Reaccion1`
    FOREIGN KEY (`Reaccion_idReaccion`)
    REFERENCES `Chat`.`Reaccion` (`idReaccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reaccion_has_Mensaje_Mensaje1`
    FOREIGN KEY (`Mensaje_idMensaje`)
    REFERENCES `Chat`.`Mensaje` (`idMensaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Chat`.`Amigo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Chat`.`Amigo` ;

CREATE TABLE IF NOT EXISTS `Chat`.`Amigo` (
  `idAmigo` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `amigoId` INT NOT NULL,
  PRIMARY KEY (`idAmigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
